- branch: WRLINUX_10_17_LTS
  build:
  - 'bitbake wrlinux-image-glibc-std ; bitbake wrlinux-image-glibc-std -c testexport'
  name: intel-x86-64_wrlinux-image-glibc-std
  prebuild:
  - notconfigure.sh
  - --oe-test=with_wrlinux10
  - --enable-shared-sstate=wrl10_sstate_cache
  - --test-suites=ping,ssh,df,connman,syslog,xorg,scp,vnc,date,pam,perl,python,rpm,ldd,smart,dmesg
  setup:
  - --distro=wrlinux
  - --machine=intel-x86-64
  - --dl-layers
  - --accept-eula=yes
- branch: WRLinux-lts-17-Base
  build:
  - bitbake
  - wrlinux-image-glibc-small
  name: qemux86-64_glibc-small_Base
  prebuild:
  - notconfigure.sh
  - --test-image=yes
  - --enable-bootimage=ext4
  - --no-network=0
  - --premirror_path=/home/wrlbuild/premirror-master-wr
  setup:
  - --distro=wrlinux-small
  - --machine=qemux86-64