- name: oeqa-default-test
  prebuild_cmd_for_test:
  - test_configure.py
  build_cmd_for_test:
  - bitbake wrlinux-image-glibc-std -c testexport
  build_options:
  - INHERIT += "testexport"
  - IMAGE_INSTALL_append += "python3-pkgutil"
  - IMAGE_INSTALL_append += "python3-unittest"
  - IMAGE_INSTALL_append += "python3-multiprocessing"
  - TEST_TARGET_IP = "localhost"
  - TEST_SERVER_IP = "localhost"
  - TEST_SUITES = "ping ssh df connman syslog xorg scp vnc date pam perl python rpm ldd smart dmesg dash"
  lava_test_repo: https://github.com/ywangwrs/lava-test.git
  aws-ec2_qemu-x86_64:
    job_template: lava-test/jobs/templates/wrlinux-10/x86_64_qemu_job_oeqa-default-test_template.yaml
    timeout: 300
  remote:
    job_template: lava-test/jobs/templates/wrlinux-10/x86_64_job_oeqa-default-test_template.yaml
    timeout: 600
  simics:
    job_template: lava-test/jobs/templates/wrlinux-10/x86_simics_job_oeqa-default-test_template.yaml
    timeout: 420
  baytrail_simics:
    job_template: lava-test/jobs/templates/wrlinux-10/x86_simics_job_oeqa-default-test_template.yaml
    timeout: 420
  x86-x58-ich10_simics:
    job_template: lava-test/jobs/templates/wrlinux-10/x86-x58-ich10_simics_job_oeqa-default-test_template.yaml
    timeout: 600
  purley_simics:
    job_template: lava-test/jobs/templates/wrlinux-10/purley_simics_job_oeqa-default-test_template.yaml
    timeout: 600

- name: oeqa-ptest
  prebuild_cmd_for_test:
  - test_configure.py
  build_cmd_for_test:
  - bitbake wrlinux-image-glibc-std -c testexport
  build_options:
  - INHERIT += "testexport"
  - IMAGE_INSTALL_append += "python3-pkgutil"
  - IMAGE_INSTALL_append += "python3-unittest"
  - IMAGE_INSTALL_append += "python3-multiprocessing"
  - TEST_TARGET_IP = "localhost"
  - TEST_SERVER_IP = "localhost"
  - TEST_SUITES = "ping ssh ptest"
  - IMAGE_FSTYPES += "ext4"
  - DISTRO_FEATURES_append = " ptest"
  - EXTRA_IMAGE_FEATURES += "ptest-pkgs"
  - CORE_IMAGE_EXTRA_INSTALL += "e2fsprogs-ptest zlib-ptest"
  lava_test_repo: https://github.com/ywangwrs/lava-test.git
  remote:
    job_template: lava-test/jobs/templates/wrlinux-10/x86_64_job_oeqa-default-test_template.yaml
    timeout: 600

- name: lsb-test
  prebuild_cmd_for_test:
  - test_configure.py
  build_cmd_for_test:
  build_options:
  - WRTEMPLATE = "feature/lsbtesting"
  - IMAGE_INSTALL_append += " rsync"
  lava_test_repo: https://github.com/ywangwrs/lava-test.git
  remote:
    job_template: lava-test/jobs/templates/wrlinux-10/x86_64_job_oeqa-default-test_template.yaml
    timeout: 600

- name: oeqa-qemuarm-test
  prebuild_cmd_for_test:
  - test_configure.py
  build_cmd_for_test:
  - bitbake wrlinux-image-glibc-std -c testexport
  build_options:
  - INHERIT += "testexport"
  - IMAGE_INSTALL_append += "python3-pkgutil"
  - IMAGE_INSTALL_append += "python3-unittest"
  - IMAGE_INSTALL_append += "python3-multiprocessing"
  - TEST_TARGET_IP = "localhost"
  - TEST_SERVER_IP = "localhost"
  - TEST_SUITES = "ping ssh df connman syslog xorg scp vnc date pam perl python rpm ldd smart dmesg dash"
  - IMAGE_FSTYPES += "ext4"
  - INHERIT += "testimage"
  - TEST_IMAGE = "1"
  - TEST_QEMUBOOT_TIMEOUT = "1500"
  lava_test_repo: https://github.com/ywangwrs/lava-test.git
  qemu-arm:
    job_template: lava-test/jobs/templates/wrlinux-10/arm_qemu_job_oeqa-default-test_template.yaml
    timeout: 420
  qemu-arm64:
    job_template: lava-test/jobs/templates/wrlinux-10/arm64_qemu_job_oeqa-default-test_template.yaml
    timeout: 420

- name: cgl-oeqa-default-test
  prebuild_cmd_for_test:
  - test_configure.py
  build_cmd_for_test:
  - bitbake wrlinux-image-glibc-cgl -c testexport
  build_options:
  - INHERIT += "testexport"
  - IMAGE_INSTALL_append += "python3-pkgutil"
  - IMAGE_INSTALL_append += "python3-unittest"
  - IMAGE_INSTALL_append += "python3-multiprocessing"
  - TEST_TARGET_IP = "localhost"
  - TEST_SERVER_IP = "localhost"
  - TEST_SUITES = "ping ssh df connman syslog xorg scp vnc date pam perl python rpm ldd smart dmesg dash"
  - INHERIT += "testimage"
  - TEST_IMAGE = "1"
  - TEST_QEMUBOOT_TIMEOUT = "1500"
  - WRTEMPLATE = "feature/gdb"
  - IMAGE_INSTALL_append += "expect"
  lava_test_repo: https://github.com/ywangwrs/lava-test.git
  aws-ec2_qemu-x86_64:
    job_template: lava-test/jobs/templates/wrlinux-10/x86_64_qemu_job_cgl-oeqa-default-test_template.yaml
    timeout: 1800

- name: cgl-vrf-test
  prebuild_cmd_for_test:
  - test_configure.py
  build_cmd_for_test:
  build_options:
  - WRTEMPLATE = "feature/gdb"
  - IMAGE_INSTALL_append += "expect"
  lava_test_repo: https://github.com/ywangwrs/lava-test.git
  aws-ec2_qemu-x86_64:
    job_template: lava-test/jobs/templates/wrlinux-10/x86_64_qemu_job_cgl-vrf-test_template.yaml
    timeout: 1800

- name: linaro-smoke-test
  prebuild_cmd_for_test:
  - test_configure.py
  build_cmd_for_test:
  build_options:
  - IMAGE_FSTYPES += "ext4"
  lava_test_repo: https://github.com/ywangwrs/lava-test.git
  aws-ec2_qemu-x86_64:
    job_template: lava-test/jobs/templates/OpenEmbedded/x86_64_qemu_job_lava-smoke-test_template.yaml
    timeout: 300
  remote:
    job_template: lava-test/jobs/templates/wrlinux-10/x86_64_job_linaro-smoke-test_template.yaml
    timeout: 300
  baytrail_simics:
    job_template: lava-test/jobs/templates/wrlinux-10/x86_simics_job_linaro-smoke-test_template.yaml
    timeout: 300
  x86-x58-ich10_simics:
    job_template: lava-test/jobs/templates/wrlinux-10/x86-x58-ich10_simics_job_linaro-smoke-test_template.yaml
    timeout: 600
  purley_simics:
    job_template: lava-test/jobs/templates/wrlinux-10/purley_simics_job_linaro-smoke-test_template.yaml
    timeout: 600
  qemu:
    job_template: lava-test/jobs/templates/wrlinux-10/x86_64_qemu_job_linaro-smoke-test_template.json
    timeout: 300

